name: "Get and cached Dependencies"
description: "Get the Dependencies(via npm) and cache them"
inputs:
  caching:
    description: "whether to use caching"
    required: false
    default: "true"
  node_version:
    description: "Node version to be used"
    required: false
    default: "20.x"
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${inputs.node_version}
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
